name: CI/CD Pipeline - Docker Hub Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Unit Tests
        run: |
          pip install flask
          python -m unittest discover -s . -p "test_*.py"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
         context: ./flask-jenkins-cicd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker_khanishk1:latest